### PR TITLE
another version of the hypercomplex script but with a complex basis

### PR DESCRIPTION
**Pull request by gravityshouldbenaut**
Hi! I made another version of the script that just uses a complex basis instead of a float basis. This was necessary for me because I wanted to be able to create systems larger than quaternions on the fly, and just wanted to be able to input complex numbers into each positions. To make this work, I also made sure that any place that used Real(num) was changed to using num.real.

### CODE REVIEW

**Comment by discretegames** [comment]
So is the goal to be able to do things like `Quaternion(1+2j, 3+4j)` instead of `Quaternion(1, 2, 3, 4)`? Plus maybe an option to print them like `(1+2j 3+4j)` instead of `(1 2 3 4)`.

I might be able to modify the `__init__` of `Hypercomplex` so it allows any sequence of float/complex/Hypercomplex and parts them out in the order given to make it work.

I'm a bit confused by your code though. It allows things like `c = Complex(1+2j, 3+4j)` which is a complex number with 4 parts? Almost feels like a quaternion but it does not behave like one. `c*c` is `(-12-8j -2+14j)` instead of `(-28 4 6 8)`.

**Comment by gravityshouldbenaut** [comment]
Yup thats the goal! 

Ah, yeah, the Complex item you created...I guess in this complex based system, the Complex could be called Bicomplex, which is a 4 part number with two complex parts, and the base could be complex instead of Real. What do you think? Here is a link to that: 
https://en.wikipedia.org/wiki/Bicomplex_number

**Comment by discretegames** [comment]
Oh interesting. I didn't know bicomplex numbers were a thing. I guess you could have biquaternions and bioctonions too? Perhaps even quadcomplex where a complex number is made up of two quaternions? I'm not sure, this math is a bit beyond me.

Let me think it over and I may accept your pull request or reimplement some things myself.

**Comment by gravityshouldbenaut** [comment]
Exactly right! Ok, sounds good, do you want me to redo the pull request with "Bicomplex" then instead of "Complex" in the hypercomplex_complexbasis file so that its clear that thats what the number would become if starting with a complex basis?

**Comment by discretegames** [comment]
Sorry but I can't accept the pull request as is since the file structure was changed and only the files originally in the hypercomplex folder are included.

Though also I don't have the time/interest to review the code (and the math) to my satisfaction as I'm not really thinking about this project anymore. So even if the file structure issues were fixed I can't promise I'd look into it. Apologies 😔

(But by all means, feel free to copy the code and structure of this project to make your own "bihypercomplex" PyPI package or something! Bicomplex numbers and beyond are a cool, weird math idea.)

**Pull request closed without merging**
